const NEXT_PUBLIC_TEMPLATE_CLIENT_ID =
  process.env.NEXT_PUBLIC_TEMPLATE_CLIENT_ID || '';
const LIVEPEER_API_KEY = process.env.LIVEPEER_API_KEY || '';
const SNAPSHOT_API_KEY = process.env.SNAPSHOT_API_KEY || '';
const THIRDWEB_ADMIN_PRIVATE_KEY = process.env.THIRDWEB_ADMIN_PRIVATE_KEY || '';
const JWT_SECRET = process.env.JWT_SECRET || '';
const WERT_PRIVATE_KEY = process.env.WERT_PRIVATE_KEY || '';
const NODE_ENV = process.env.NODE_ENV || '';

export {
  JWT_SECRET,
  LIVEPEER_API_KEY,
  NEXT_PUBLIC_TEMPLATE_CLIENT_ID,
  NODE_ENV,
  SNAPSHOT_API_KEY,
  THIRDWEB_ADMIN_PRIVATE_KEY,
  WERT_PRIVATE_KEY,
};
